# fly.toml app configuration file generated for ebookmode on 2024-03-27T22:01:36Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ebookmode'
primary_region = 'mad'
swap_size_mb = 256

[build]
  build-target = 'production'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
